import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
  en: { translation: {
    appName: 'Doti', welcome: 'Your simple space for everyday things.',
    navigation: { tasks: 'Tasks', birthdays: 'Birthdays', notes: 'Notes', completed: 'Completed', settings: 'Settings' },
    placeholder: 'This screen is ready for the next phase.',
    tasks: { today: 'Today', later: 'Later', add: 'Add task', quickAdd: 'What needs doing?', upcomingBirthdays: 'Upcoming birthdays', more: 'More actions' },
    taskDetail: { backToTasks: 'Back to Tasks', loading: 'Loading...', notFound: 'Task not found', status: 'Status', priority: 'Priority', created: 'Created', due: 'Due', completed: 'Completed', description: 'Description', edit: 'Edit', preview: 'Preview', addDescription: 'Add a description...', delete: 'Delete Task', confirmDelete: 'Delete this task? This cannot be undone from the current UI.', cancel: 'Cancel', complete: 'Complete task', restore: 'Restore task', moveToLater: 'Move task to later', moveToToday: 'Move task to today', changePriority: 'Change priority', hasDescription: 'Has description', priorityGreen: 'Green priority', priorityYellow: 'Yellow priority', priorityOrange: 'Orange priority', priorityRed: 'Red priority' },
    birthdays: { today: 'Today', tomorrow: 'Tomorrow', days: '{{count}} days', addTitle: 'Add Birthday', editTitle: 'Edit Birthday', name: 'Name', month: 'Month', day: 'Day', add: 'Add', save: 'Save', cancel: 'Cancel', delete: 'Delete Birthday', confirmDelete: 'Delete this birthday?', empty: 'No birthdays yet', seeAll: 'See all', nameRequired: 'Enter a name.', invalidDay: 'Enter a valid day.' },
    notes: { search: 'Search notes...', addTitle: 'Add note', untitled: 'Untitled', updated: 'Updated', updatedToday: 'Updated today', empty: 'No notes yet', noResults: 'No notes found', loading: 'Loading...', startWriting: 'Start writing...', backToNotes: 'Back to Notes', notFound: 'Note not found', delete: 'Delete Note', confirmDelete: 'Delete this note? This cannot be undone from the current UI.' },
    links: { linkedNotes: 'Linked Notes', linkedTasks: 'Linked Tasks', linkNote: 'Link a note', linkTask: 'Link a task', searchNotes: 'Search notes...', searchTasks: 'Search tasks...', createNote: 'Create new note', createTask: 'Create new task', noLinkedNotes: 'No linked notes', noLinkedTasks: 'No linked tasks', noNotesAvailable: 'No notes available', noTasksAvailable: 'No tasks available', unlink: 'Unlink', taskTitle: 'Task title', create: 'Create', cancel: 'Cancel' },
    habits: { title: 'Habits', add: 'Add habit', name: 'Habit name', empty: 'No habits yet', nothingToday: 'Nothing scheduled today', edit: 'Edit Habit', repeat: 'Repeat', daily: 'Every day', selectedDays: 'Selected days', weekdayShort: ['M', 'T', 'W', 'T', 'F', 'S', 'S'], delete: 'Delete Habit', confirmDelete: 'Delete this habit?', cancel: 'Cancel', save: 'Save', check: 'Mark {{name}} complete', uncheck: 'Mark {{name}} incomplete' },
    completed: { title: 'Completed Tasks', today: 'Today', yesterday: 'Yesterday', completed: 'Completed', restore: 'Restore', empty: 'No completed tasks yet' },
    settings: { title: 'Settings', appearance: 'Appearance', tasks: 'Tasks', dashboard: 'Dashboard', showHabitsOnDashboard: 'Show Habits on Dashboard', data: 'Data', about: 'About', language: 'Language', theme: 'Theme', system: 'System', light: 'Light', dark: 'Dark', english: 'English', spanish: 'Spanish', accentColor: 'Accent Color', priorityAging: 'Priority Aging', priorityAgingHelp: 'Automatically increases the priority of tasks that remain pending. Changing a task’s priority manually restarts its aging period.', agingInterval: 'Aging Interval', days: '{{count}} days', exportData: 'Export Data', importData: 'Import Data', exportSuccess: 'Backup exported successfully.', restoreConfirm: 'Restore backup? This will replace all current Doti data with the contents of the selected backup.', restoreSuccess: 'Backup restored successfully.', invalidBackup: 'Invalid Doti backup file.', newerBackup: 'This backup was created by a newer version of Doti.', exportError: 'Could not export Doti data.', restoreError: 'Could not restore Doti data.', version: 'Version', colors: { blue: 'Blue', purple: 'Purple', pink: 'Pink', green: 'Green', orange: 'Orange', teal: 'Teal' } },
    sync: { title: 'Sync', description: 'Keep Doti in sync across your devices.', email: 'Email', password: 'Password', signIn: 'Sign in', createAccount: 'Create account', signOut: 'Sign out', connectedAs: 'Connected as', syncNow: 'Sync now', syncing: 'Syncing...', synced: 'Synced', lastSynced: 'Last synced', never: 'Never', offline: 'Offline', syncFailed: 'Sync failed. Try again.', checkEmail: 'Check your email to confirm your Doti account.', accountCreated: 'Account created.', invalidCredentials: 'Invalid email or password.', differentAccount: 'A different account is already associated with this local Doti data. Use a separate browser profile or back up and reset local data before switching accounts.', notConfigured: 'Sync is not configured yet.' },
  } },
  es: { translation: {
    appName: 'Doti', welcome: 'Tu espacio simple para las cosas de todos los días.',
    navigation: { tasks: 'Tareas', birthdays: 'Cumpleaños', notes: 'Notas', completed: 'Completadas', settings: 'Configuración' },
    placeholder: 'Esta pantalla está lista para la próxima fase.',
    tasks: { today: 'Hoy', later: 'Más tarde', add: 'Agregar tarea', quickAdd: '¿Qué hay que hacer?', upcomingBirthdays: 'Próximos cumpleaños', more: 'Más acciones' },
    taskDetail: { backToTasks: 'Volver a tareas', loading: 'Cargando...', notFound: 'Tarea no encontrada', status: 'Estado', priority: 'Prioridad', created: 'Creada', due: 'Vencimiento', completed: 'Completada', description: 'Descripción', edit: 'Editar', preview: 'Vista previa', addDescription: 'Agregar una descripción...', delete: 'Eliminar tarea', confirmDelete: '¿Eliminar esta tarea? Esta acción no se puede deshacer desde la interfaz actual.', cancel: 'Cancelar', complete: 'Completar tarea', restore: 'Restaurar tarea', moveToLater: 'Mover tarea a más tarde', moveToToday: 'Mover tarea a hoy', changePriority: 'Cambiar prioridad', hasDescription: 'Tiene descripción', priorityGreen: 'Prioridad verde', priorityYellow: 'Prioridad amarilla', priorityOrange: 'Prioridad naranja', priorityRed: 'Prioridad roja' },
    birthdays: { today: 'Hoy', tomorrow: 'Mañana', days: '{{count}} días', addTitle: 'Agregar cumpleaños', editTitle: 'Editar cumpleaños', name: 'Nombre', month: 'Mes', day: 'Día', add: 'Agregar', save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar cumpleaños', confirmDelete: '¿Eliminar este cumpleaños?', empty: 'No hay cumpleaños todavía', seeAll: 'Ver todos', nameRequired: 'Ingresa un nombre.', invalidDay: 'Ingresa un día válido.' },
    notes: { search: 'Buscar notas...', addTitle: 'Agregar nota', untitled: 'Sin título', updated: 'Actualizada', updatedToday: 'Actualizada hoy', empty: 'Aún no hay notas', noResults: 'No se encontraron notas', loading: 'Cargando...', startWriting: 'Empieza a escribir...', backToNotes: 'Volver a notas', notFound: 'Nota no encontrada', delete: 'Eliminar nota', confirmDelete: '¿Eliminar esta nota? Esta acción no se puede deshacer desde la interfaz actual.' },
    links: { linkedNotes: 'Notas vinculadas', linkedTasks: 'Tareas vinculadas', linkNote: 'Vincular una nota', linkTask: 'Vincular una tarea', searchNotes: 'Buscar notas...', searchTasks: 'Buscar tareas...', createNote: 'Crear nueva nota', createTask: 'Crear nueva tarea', noLinkedNotes: 'No hay notas vinculadas', noLinkedTasks: 'No hay tareas vinculadas', noNotesAvailable: 'No hay notas disponibles', noTasksAvailable: 'No hay tareas disponibles', unlink: 'Desvincular', taskTitle: 'Título de la tarea', create: 'Crear', cancel: 'Cancelar' },
    habits: { title: 'Hábitos', add: 'Agregar hábito', name: 'Nombre del hábito', empty: 'Aún no hay hábitos', nothingToday: 'No hay nada programado para hoy', edit: 'Editar hábito', repeat: 'Repetición', daily: 'Todos los días', selectedDays: 'Días seleccionados', weekdayShort: ['L', 'M', 'X', 'J', 'V', 'S', 'D'], delete: 'Eliminar hábito', confirmDelete: '¿Eliminar este hábito?', cancel: 'Cancelar', save: 'Guardar', check: 'Marcar {{name}} como completado', uncheck: 'Marcar {{name}} como incompleto' },
    completed: { title: 'Tareas completadas', today: 'Hoy', yesterday: 'Ayer', completed: 'Completada', restore: 'Restaurar', empty: 'Aún no hay tareas completadas' },
    settings: { title: 'Configuración', appearance: 'Apariencia', tasks: 'Tareas', dashboard: 'Panel', showHabitsOnDashboard: 'Mostrar hábitos en el panel', data: 'Datos', about: 'Acerca de', language: 'Idioma', theme: 'Tema', system: 'Sistema', light: 'Claro', dark: 'Oscuro', english: 'Inglés', spanish: 'Español', accentColor: 'Color de acento', priorityAging: 'Antigüedad de prioridad', priorityAgingHelp: 'Aumenta automáticamente la prioridad de las tareas que permanecen pendientes. Cambiar manualmente la prioridad reinicia su período de antigüedad.', agingInterval: 'Intervalo de antigüedad', days: '{{count}} días', exportData: 'Exportar datos', importData: 'Importar datos', exportSuccess: 'Respaldo exportado correctamente.', restoreConfirm: '¿Restaurar respaldo? Esto reemplazará todos los datos actuales de Doti con el contenido del respaldo seleccionado.', restoreSuccess: 'Respaldo restaurado correctamente.', invalidBackup: 'Archivo de respaldo de Doti no válido.', newerBackup: 'Este respaldo fue creado por una versión más reciente de Doti.', exportError: 'No se pudieron exportar los datos de Doti.', restoreError: 'No se pudieron restaurar los datos de Doti.', version: 'Versión', colors: { blue: 'Azul', purple: 'Violeta', pink: 'Rosa', green: 'Verde', orange: 'Naranja', teal: 'Verde azulado' } },
    sync: { title: 'Sincronización', description: 'Mantén Doti sincronizado entre tus dispositivos.', email: 'Correo electrónico', password: 'Contraseña', signIn: 'Iniciar sesión', createAccount: 'Crear cuenta', signOut: 'Cerrar sesión', connectedAs: 'Conectado como', syncNow: 'Sincronizar ahora', syncing: 'Sincronizando...', synced: 'Sincronizado', lastSynced: 'Última sincronización', never: 'Nunca', offline: 'Sin conexión', syncFailed: 'La sincronización falló. Inténtalo de nuevo.', checkEmail: 'Revisa tu correo para confirmar tu cuenta de Doti.', accountCreated: 'Cuenta creada.', invalidCredentials: 'Correo o contraseña no válidos.', differentAccount: 'Ya hay otra cuenta asociada con estos datos locales de Doti. Usa otro perfil del navegador o respalda y restablece los datos locales antes de cambiar de cuenta.', notConfigured: 'La sincronización todavía no está configurada.' },
  } },
}

void i18n.use(initReactI18next).init({
  resources,
  lng: 'en',
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
})

export default i18n
